device: 0
metric: ACC
dataset:
  format: PyG
  name: REDDIT-BINARY
train:
  batch_size: 64
  stopping_patience: 100
  loss_fn: cross_entropy
gnn:
  num_layers: 4
  hidden_dim: 64
  layer_type: GIN
  pool: mean
  dropout: 0.5
optim:
  optimiser: adam
  base_lr: 0.001
  max_epochs: 300
  scheduler: 'reduce_on_plateau'
